server:
    port: 9091
    context-path: #/balcklist/

logging:
    level:
        tk.mybatis: TRACE

druid:
    url: jdbc:mysql://localhost:3306/blacklist?useUnicode=true&characterEncoding=utf-8
    username:
    password:
    initial-size: 1
    min-idle: 1
    max-active: 120
    test-on-borrow: true

spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: com.bhusk.black.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.bhusk.black.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

spring:
    mail:
        host: mail.qiye.aliyun.com
        username: black@bhusk.com
        password: password
        default-encoding: UTF-8
        properties.mail.smtp.auth: true
        properties.mail.smtp.starttls.enable: false
        properties.mail.smtp.starttls.required: false
